### ISSUE TITLE
The certificate of api.botan.io has expired

### ISSUE THREAD

**Issue by mokcrimea** [botanio/sdk#113]
![image](https://user-images.githubusercontent.com/725846/37894418-e2df1b80-30e6-11e8-8143-cf69d995179a.png)

**Comment by xvadsan** [comment]
When you will fix that problen?

**Comment by mokcrimea** [comment]
It's updated:
![image](https://user-images.githubusercontent.com/725846/37998711-609a067e-3228-11e8-9ac2-74378af2974f.png)
