### ISSUE TITLE
Обработка на стороне сервиса гео информации с ботов

### ISSUE THREAD

**Issue by SonkoDmitry** [botanio/sdk#13]
Отправил человек геолокацию, было-бы очень неплохо, чтобы именно она учитывалась все в географии пользователей в аналитике, а не ип адрес где размещен бэкенд бота. Таким образом, можно было-бы строить аналитики и по странам городам

**Comment by yaroshevsky** [comment]
Да, будем делать

**Comment by SonkoDmitry** [comment]
Я правильно понимаю, что сейчас группировка по пользователям идет на основании uid, который сбрасывается на трекер?

**Comment by ollmer** [comment]
Да

**Comment by SonkoDmitry** [comment]
Есть у вас какой-то роадмап по разработке и фичам? Дабы знать к чему готовиться.

**Comment by yaroshevsky** [comment]
Пока собираем обратную связь. А какие фичи нужны?

**Comment by SonkoDmitry** [comment]
Из краткого знакомства с сервисом, крутилось гео. Раз будет - хорошо. Может у вас еще козыри в рукаве есть?

**Comment by yaroshevsky** [comment]
Платформа новая, всё меняется быстро, поэтому мы предпочитаем сейчас сильно не загадывать, а лучше внимательно слушать первых пользователей. Если будут еще идеи – будем признательны!

**Comment by SonkoDmitry** [comment]
Чего сильно не хватает, дак это нативной информации об устройстве пользователя от телеграмма. У меня в бота именно для этого сделаны шортлинки, по которым на основании юзер агента идет определение устройства.
Второе, источник траффика. Я это мониторю через параметр к команде старт telegram.me/botname?start=traffic_source. Было бы неплохо "прокидывать" эти данные в аналитику, но я так понимаю, необходимо вводить некие типы принимаемых данных на стороне вашего бэкенда.

**Comment by Kondra007** [comment]
Добавлю от себя 5 копеек: почему бы не анализировать first_name у пользователя и, исходя из этого, отмечать его пол в статистике? 
Сейчас большинство полей просто лишние для TG-ботов.

**Comment by IPRIT** [comment]
@kondra007, определить пол по first_name - плохая идея. 20% запросов к ботам - арабскими пользователями. Русских пользователей процентов 5. Почти 30% имеют не настоящий first_name, т. е. псевдоним, а иногда просто смайлик.

**Comment by IPRIT** [comment]
Даже если суметь у какого-то процента пользователей определить пол, то данные ничего не будут показывать, так как это будет далеко не средний результат.

**Comment by yaroshevsky** [comment]
Про источник траффика мне понравилось, возьмем на вооружение, спасибо!

**Comment by SonkoDmitry** [comment]
Рад стараться! Вот можно было-бы его прокидывать еще в аналитику как источник - было бы супер.

**Comment by ihoru** [comment]
@yaroshevsky можно для начала реализовать сбор геоданных на основе объекта location ( https://core.telegram.org/bots/api#location ) присылаемого пользователем. Бот может просто спросить пользователя прислать геолокацию для... (напишите свое) и раз и на всегда (до следующего присланного объекта локации) привязать эту локацию к пользователю.

**Comment by aidarbiktimirov** [comment]
Сделали сокращалку ссылок - теперь она позволяет прокидывать локацию/ос/устройство пользователя в аппметрику.
