### ISSUE TITLE
AppMetrica Api key is not secure

### ISSUE THREAD

**Issue by ihoru** [botanio/sdk#14]
Было бы неплохо чтобы апи кей метрики был не тем же самым, что id, а какими-то уникальным хэшом.
Я понимаю, почему он такой для клиентских приложений на андроид и иос, но в случае с Телеграмом запросы делаются сервер-сервер, поэтому его можно сделать безопаснее, чтобы никто не нафлудил тебе в статистику случайно или со злым умыслом.

**Comment by yaroshevsky** [comment]
Да, API key метрики скоро поменяется в корне. Спасибо за фидбек!

**Comment by SonkoDmitry** [comment]
Главное рассылку делайте перед изменением формата :-) ибо у многих сломается увсё)

**Comment by lososerg** [comment]
Друзья, а Ботан работает? За 22 августа 0 посетителей, не смотря на то, что они есть. API Key в настройках прежний.

**Comment by ollmer** [comment]
Доброе утро! Да, ночью были проблемы с метрикой, сейчас уже всё восстановили. События с 22:00 вчерашнего дня должны отображаться нормально. События вчерашнего на интервале 19:00-22:00 будут восстановлены немного позже.
