### ISSUE TITLE
Call to undefined function curl_init()

### ISSUE THREAD

**Issue by pupadupa** [botanio/sdk#17]
Для php видимо надо указать, что есть завивсимость от php5-curl, если не установлен модуль, то выскакивает `Call to undefined function curl_init()       Botan.php on line 43`

На ubuntu решается так: 
`sudo apt-get install php5-curl`

**Comment by IPRIT** [comment]
Попробуй такой вариант: https://github.com/IPRIT/sdk/tree/patch-3

**Comment by ollmer** [comment]
Долили патч в мастер: https://github.com/botanio/sdk/commit/4388c4bf65362795f6ac5c87588a8434801d57ca
