### ISSUE TITLE
Странные записи в Метрике

### ISSUE THREAD

**Issue by Kondra007** [botanio/sdk#19]
Здравствуйте.
Заметил сегодня, что в Метрике для всех моих ботов появились странные записи с какими-то хэшами, хотя, по идее, должны выводиться только записи для указанных команд в функции `botan.track`

Вот [скриншот](https://pp.vk.me/c621916/v621916512/37ee4/RNGeQoYbXZc.jpg) этого безобразия.
Во всех случаях такой мусор идет от юзера Test test c id 615946

Каждый такой хэш отмечается в статистике ровно один раз.

**Comment by ihoru** [comment]
У меня тоже самое было!

**Comment by malishev** [comment]
Да, и у меня тоже самое

**Comment by Kondra007** [comment]
Что ж, видимо, неизвестный добился своей цели - его заметили.
@IPRIT, что скажете?

**Comment by ollmer** [comment]
@Kondra007 это скорее ко мне, а не к IPRIT. 
Вчера около 20:00 какой-то энтузиаст начал эксплуатировать перебор коротких токенов и слать левые события. Мы забанили его после полуночи, обнаружив это непотребство.

Так дальше жить нельзя, поэтому в ближайшее время переводимся на механизм длинных случайных токенов.Сегодня вечером напишу о механизме миграции на новые токены. 

Старые ключи будут работать еще неделю после запуска новых, но останутся уязвимы к подобной атаке.

Приношу извинения от нашей команды за эти неудобства.

**Comment by Kondra007** [comment]
@ollmer Олег, спасибо за комментарий и за оперативность! 
Можно ли Вас попросить удалить из наших метрик эти события? К сожалению, у меня самого это сделать не получилось, при выборе событий галочками нет никакой возможности их удалить.

**Comment by ollmer** [comment]
Да, сейчас выясняем этот вопрос.

**Comment by iGusev** [comment]
>Мы забанили его после полуночи, обнаружив это непотребство.

Так он даже помог, ведь "пока гром не грянет, мужик не перекрестится". Забанили зря

**Comment by ollmer** [comment]
Мы планируем добавить еще один шаг в процедуру начала работы с метрикой. После получения апи ключа необходимо будет отправить его нашему боту в телеграме. Имя бота будет в мануале по подключению. Спустя некоторое время этот бот пришлет вам в ответ длинный токен, который и надо будет использовать в вызовах sdk вместо старого токена.

При этом для уже подключенных ботов старый апикей будет работать на протяжении неделе с момента запуска новой схемы. О запуске я напишу отдельно.

**Comment by ollmer** [comment]
Длинные ключи доступны для использования. Короткие ключи пока тоже работают, о сроках прекращения их поддержки сообщим чуть позже.
