### ISSUE TITLE
explanation of API

### ISSUE THREAD

**Issue by dcsan** [botanio/sdk#23]
you have "Start" as an example event. is this word meaningful or can we change that to be different tracking event names "signup", "game", "levelup" etc. ?

wondering how we can send more meaningful data to the API for tracking...

**Comment by dcsan** [comment]
ok well i just wired it up and those events show up by name so i guess we can call them anything.

are there any funnels in the yandex API? sorry i havent used it until now. you're the first bot specific tool ive seen!

**Comment by ollmer** [comment]
Hi. Thanks for using our service. We are currently don't have funnels analytics tools, but planning to make them later.
