### ISSUE TITLE
Запросы с c9.io блокируются api.botan.io

### ISSUE THREAD

**Issue by IPRIT** [botanio/sdk#26]
Ботан блокирует все запросы из онлайн IDE https://c9.io
```js
response.statusCode: 403
response.statusText: undefined
```

**Comment by ollmer** [comment]
Можно поподробнее, что значит блокирует? У cloud9 есть какая-то виртуалка, и запросы с выполняющегося на ней кода возвращают 403?

**Comment by IPRIT** [comment]
@ollmer Верно!

**Comment by ollmer** [comment]
А можно её айпи? И запросы точно по https?

**Comment by IPRIT** [comment]
@ollmer, Remote Address:146.148.18.199:443. Точно https.

**Comment by ollmer** [comment]
И время последних запросов, пожалуйста.

**Comment by IPRIT** [comment]
Да минут 15 назад.

**Comment by ollmer** [comment]
У нас в логах вообще не видно запросов с это айпи-адреса. Возможно, cloud9 сам блокирует запросы из виртуалок наружу? Стоит спросить у их поддержки.

**Comment by Kondra007** [comment]
Взято отсюда: https://c9.io/blog/can-i-use-cloud9-to-do-x/

$PORT is exposed to the outside: When you run an application which listens on the port specified in the environment variable $PORT, you can access this application using the http://projectname-username.c9.io URL scheme. The proxy expects the server on that port to be an HTTP server. Other protocols are not supported.

Мне кажется, или причина в этом?

**Comment by IPRIT** [comment]
@Kondra007, нет, не в этом. Запросы я отправляю к своему API -- все нормально, а вот к botan -- ненормально? Бред. Создал новый Workspace -- все работает как надо.
