### ISSUE TITLE
How fast data will arrive to botan?

### ISSUE THREAD

**Issue by akmalabbasov** [botanio/sdk#32]
Hi, I am using ruby `telegram-bot-api` wrapper, and sending info to `botan`. I don't have any errors while invoking `track` method, but the problem is I can't see any data in my dashboard. Is there any delay? 
p.s. I've waiter for ~10 minuts, and still there is no data.
Thank you.

**Comment by bluzir** [comment]
I have same issue, but there is no any data for the whole day.

**Comment by ollmer** [comment]
Hello! Please mail us your tokens to the team@botan.io, we will check what`s going on.

**Comment by ollmer** [comment]
We`ve had some problems with tracking long tokens. Now it`s fixed and everything seems to be fine. Data will arrive 5-10 minutes after sending. Sorry for inconvenience.

**Comment by akmalabbasov** [comment]
@ollmer , great! It is working now. Thank you!
