### ISSUE TITLE
Что там с ключами?

### ISSUE THREAD

**Issue by SerjoPepper** [botanio/sdk#33]
Видел, что перегенерили ключи, но когда именно, не понял.
1. Почему не оповестили по почте о новых ключах?
2. Когда точно старые ключи отвалятся?

**Comment by aidarbiktimirov** [comment]
Старые токены отключать не будем, просто теперь более предпочтителен вариант генерации токенов через бота

**Comment by aidarbiktimirov** [comment]
Посмотрел на дату треда - кажется, я ответил не на тот вопрос :)
