### ISSUE TITLE
API is not responsing

### ISSUE THREAD

**Issue by ihoru** [botanio/sdk#35]
Прямо сейчас api.botan.io не отвечает на запросы (и несколько раз в течении сегодняшнего дня были такие же проблемы временами).

При чем, что самое странное, ограничение по таймауту в curl не срабатывает при тесте:
$ time curl -I --connect-timeout 1 'https://api.botan.io/track?token=TOKEN&uid=1&name=test'
^C

real	0m29.395s

Вместо TOKEN использую реальный (секретный) токен взятый с appmetrica.yandex.com .
Из-за этого бот перестает работать. Приходится отключать логирование.
Судя по тому, что некоторые боты перестают отвечать на запросы я не одинок.

WTF?

**Comment by ihoru** [comment]
Сейчас заработал. До этого АПИ не отвечал в течении как минимум 1 ч 2 мин

**Comment by ollmer** [comment]
Странно, мы не видим на мониторингах увеличения времени ответа в этот период. Напишите пожалуйста ваш IP и апи-ключ на team@botan.io, попробуем разобраться.
