### ISSUE TITLE
[PHP] accept message object

### ISSUE THREAD

**Issue by LibertyPaul** [botanio/sdk#39]
Function track($message, $event_name = 'Message') only accept key - value array in $message parameter. It would be nice to let programmers pass object, which created by json_decode($json, false).
Why all should use non-default behaviour of json_decode?

**Comment by hkrahi** [comment]
I accept

**Comment by ziahot935** [comment]
Give

**Comment by ziahot935** [comment]
Drive

**Comment by ferfarz** [comment]
Hogan

**Comment by LibertyPaul** [comment]
Guys, if you haven't got anything concrete to say - please, don't do it.

**Comment by ollmer** [comment]
Hi, Paul. 
Feel free to make pull request with this fix, if its still actual. We are open to any useful contributions.
