### ISSUE TITLE
URL shortener returns different URLs for the same input

### ISSUE THREAD

**Issue by knsd** [botanio/sdk#50]
```
$ http https://api.botan.io/s/\?token\=\$TOKEN\&url\=http://ya.ru\&user_ids\=1000
HTTP/1.1 200 OK
Connection: keep-alive
Date: Tue, 12 Jan 2016 05:20:36 GMT
Server: nginx/1.9.9
Transfer-Encoding: chunked

https://telgr.me/wDi4HWrQ

$ http https://api.botan.io/s/\?token\=\$TOKEN\&url\=http://ya.ru\&user_ids\=1000
HTTP/1.1 200 OK
Connection: keep-alive
Date: Tue, 12 Jan 2016 05:20:37 GMT
Server: nginx/1.9.9
Transfer-Encoding: chunked

https://telgr.me/wWfNIm55

$
```

A quote from the documentation:

```
You create unique short link for each pair (user, link).
```

**Comment by ollmer** [comment]
It's unique in both cases. We haven't stated that link will be consistent
between calls. I can't see any drawbacks in this behavior. If you do,
please explain.

вт, 12 Янв 2016, 9:02, Fedor Gogolev <notifications@github.com>:

**Comment by knsd** [comment]
Mm, looks like I've just misunderstood documentation. The only drawback is exhaustion of short urls. Anyway consistency between calls make sense only for (token, user, link).
