### ISSUE TITLE
Inconsistent requests

### ISSUE THREAD

**Issue by knsd** [botanio/sdk#51]
`/track/` request requires POST method but `/s/` request requires `GET`, as shown in #50 `/s/` is a quite heavy request, I suggest to use `POST` method only.

Furthermore, since telegram support supergroups and maximum user id length is 10 bytes for now, there is `user_ids` query parameter's length up to 10999 bytes which is more than your nginx server support, so it's possible to get nginx `414 Request-URI Too Large` response.

**Comment by aidarbiktimirov** [comment]
Fixed - you can send all the params in the body of a POST request:
`curl 'https://api.botan.io/s/' -X POST -d 'token=test&user_ids=1&url=http://github.com'`
