### ISSUE TITLE
Inconsistent responses

### ISSUE THREAD

**Issue by knsd** [botanio/sdk#52]
For error response `/track/` returns `"status": "bad request"` and additional info in `info` field, `/s/` returns additional info in `message` field.

For success response `/track/` returns `"status": "accepted"` and `/s/` returns plain text response. I think it's better if `/s/` could be more consistent, e.g. return json response.

Moreover as mentioned in documentation, `status` is the success indicator in `/track/` request but in `/s/` request it's just an HTTP response code.

**Comment by aidarbiktimirov** [comment]
Renamed `message` field to `info` for `/s/`.

I wouldn't like to change response structure for successful `/s/` request for two reasons:
Firstly, I'd like shortener to be as simple as possible. Secondly, if I change it now - it'll break backward compatibility for those who already started using out shortener.

If you really think it should be changed, please reopen the issue.
