### ISSUE TITLE
Botan & Stats in Yandex AppMetrica

### ISSUE THREAD

**Issue by nzhiltsov** [botanio/sdk#57]
Hi,

how to pass additional parameters for events and show them in the Yandex AppMetrica UI?

I use Java SDK and see the 'message' parameter (of type Object) in 'botan.track' method. However, neither Map, nor JSON formatted String work for it as values.

**Comment by aidarbiktimirov** [comment]
There's an example of SDK usage for Java: https://github.com/botanio/sdk/blob/master/java/sdk/src/test/java/io/botan/sdk/BotanTest.java#L55

**Comment by nzhiltsov** [comment]
Ah, OK, thanks. java.util.Map works out too.
