### ISSUE TITLE
What does "search" mean in examples?

### ISSUE THREAD

**Issue by Kondra007** [botanio/sdk#6]
Let's see example of python sdk:
`print botan.track(token, uid, messageDict, 'Search')`
What is 'Search' string for? Default value?

**Comment by IPRIT** [comment]
'Search' is the event name that will be displayed in the statistics. For Telegram it will be something like: /search
!(s)[http://s.twosphere.ru/screenshots/08-07-15_20-58-54.png]

**Comment by Kondra007** [comment]
Thank you! Could you also comment on #8 ?
