### ISSUE TITLE
All bots disappeared from @botaniobot

### ISSUE THREAD

**Issue by jacklul** [botanio/sdk#68]
All my bots disappeared from @botaniobot, /import doesn't work. Is this an issues on your end?
I can see stats in Appmetrica.

Also, so much for "We can't respond immediately but we make sure we do reply to everyone!" in @botansupportbot, I still didn't get a reply for a question asked months ago.
That bot seem to not even reply to /start command.

Posting this here because I couldn't find any other place to post this.

**Comment by aidarbiktimirov** [comment]
Hello,
We've got some problems with our db, so some of info about who's the owner of bots is lost, but we've fixed /import command and you should be able to import your bots back.
