### ISSUE TITLE
Which fields do botan need?

### ISSUE THREAD

**Issue by Kondra007** [botanio/sdk#8]
Hello, I'm using custom wrapper - [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI). It's really simple and cool, but it converts message's JSON to it's own class Message.

Which fields (e.g. chat_id, text, date, message_id...) are required for Botan's proper work? 
I just don't want to do monkeypatching and convert Message object to JSON again.

**Comment by IPRIT** [comment]
For successful operation it is enough to initialize these fields:
```
botan.track({message_id: 1, from: {}, chat: {}}, 'Start');
```

**Comment by Kondra007** [comment]
Thank you!

**Comment by Kondra007** [comment]
I've formed this JSON and passed to json.dumps():
{'from': {'first_name': 'Name', 'id': 123, 'username': 'mynickname'}, 'message_id': 17, 'chat': {'first_name': 'Name', 'id': 123}} (of course, I've replaced my data here)

And I get {'status': 'bad request'} error.
What is missing?

**Comment by Kondra007** [comment]
Ok, I've finally solved my problem. Token is Metrica's token, not Telegram's one
