### ISSUE TITLE
Critical problem with shorten url - "site https://telgr.me is in the blacklist"

### ISSUE THREAD

**Issue by a-a-k** [botanio/sdk#82]
A few days ago it happened first time and still actually. Fix it please!

![photo_2016-11-06_13-38-46](https://cloud.githubusercontent.com/assets/5455861/20035839/2dc46356-a427-11e6-9e6d-6188626f1a32.jpg)
![photo_2016-11-06_13-38-55](https://cloud.githubusercontent.com/assets/5455861/20035843/3aa955b8-a427-11e6-82ba-26f7277012ec.jpg)

**Comment by toby3d** [comment]
@a-a-k It's a not Yandex problem. Kick you internet provider for unblock resource.
P.S.: Fkng roskompozor...

**Comment by a-a-k** [comment]
@toby3d, 
then all mobile providers must be kicked too. If this domen in blacklist in cause of judgement then no difference between any providers. It can be solved by judgment only.

**Comment by toby3d** [comment]
@a-a-k Again - this is a not a Yandex problem. I don't have blocks and other problems with botan shorten urls in my bot.

**Comment by a-a-k** [comment]
Take a look here
https://antizapret.info/ip.php?ip=46.101.217.169

**Comment by dobeerman** [comment]
Really, telgr.me is blocked **in whole Russia**.

**Comment by a-a-k** [comment]
The project is dead in any case
